name: slide_item
description: The Flutter ListView's Item sliding component. You don’t need to change the existing code, you only need to wrap the original Widget with two widgets provided by this package
version: 1.0.7
homepage: https://github.com/tsx1453/slide_item

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

